CREATE FULLTEXT INDEX ADDRESS_ADDRESS ON ADDRESS(ADDRESS)
	TEXT ANALYSIS ON
	CONFIGURATION 'LINGANALYSIS_STEMS';

CREATE COLUMN TABLE "TERM_MAPPING" ("MAPPING_ID" VARCHAR(255) PRIMARY KEY,
     "LIST_ID" VARCHAR(255) NOT NULL,
     "LANGUAGE_CODE" VARCHAR(255),
     "TERM_1" VARCHAR(255) NOT NULL,
     "TERM_2" VARCHAR(255) NOT NULL,
     "WEIGHT" DECIMAL NOT NULL);